GET http://127.0.0.1:8000/products/ HTTP/1.1

###

GET http://127.0.0.1:8000/products/2 HTTP/1.1

###

DELETE http://127.0.0.1:8000/products/2 HTTP/1.1

###

PUT http://127.0.0.1:8000/products/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1Njc4ODI1LCJpYXQiOjE3NDU2Nzg1MjUsImp0aSI6IjQwMWYyODk1ZTc1MzRlZTVhZDEwZGNjMGM3MWZhMGIwIiwidXNlcl9pZCI6MX0.sCCzf6LT6wf0wCol4H-Q-LFbUviUNMQXkE_4VpoLEpQ

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###

POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1Njc2MjI5LCJpYXQiOjE3NDU2NzU5MjksImp0aSI6IjkxMWNkYTdlYTNmOTRmOGVhNDYwMzU5MDBmMGM3YzkzIiwidXNlcl9pZCI6Mn0.Am4mUft8sJ4pkGAOby2nXdaZbVrh5-P-CDYavfsxI24

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###

POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

###

POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NTc2MzIyMSwiaWF0IjoxNzQ1Njc2ODIxLCJqdGkiOiIyYjc5ZGY3MTM4ZGQ0OTE2OWQ0ZGM3YTQ2MjQ1NjFhNSIsInVzZXJfaWQiOjF9.Q52OCTG6h1fxZMC77dCEGuz28Grdk6sN51iCndQNgto"
}

###

GET http://127.0.0.1:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1Njc2MjI5LCJpYXQiOjE3NDU2NzU5MjksImp0aSI6IjkxMWNkYTdlYTNmOTRmOGVhNDYwMzU5MDBmMGM3YzkzIiwidXNlcl9pZCI6Mn0.Am4mUft8sJ4pkGAOby2nXdaZbVrh5-P-CDYavfsxI24

